import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";
import "./globals.css";
import NavBar from "@/app/components/Navbar";
import Footer from "@/app/components/Footer";

const fira = Fira_Code({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fira.className} antialiased bg-neutral-900 text-neutral-200`}
      >
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
