import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function BlogPostLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <article className="prose prose-headings:text-neutral-300 text-neutral-200 container max-w-4xl">
      {children}
    </article>
  );
}
